index:
    path: /
    controller: App\Controller\LangueController::configureLangueAction
    requirements:
        _locale: en|fr|de

authorizenet_payment_routes:
    resource: .
    type: authorizenet